name: PacketLogger
author: shoghicp & iTX Technologies LLC
api: 2.0.0
version: 1.3.0
main: shoghicp\PacketLogger\PacketLogger
description: Manage network packets as you want
website: https://github.com/iTXTech/PacketLogger